### ISSUE TITLE
InvalidArgumentException not being handled ContentValidationListener onRoute method

### ISSUE THREAD

**Issue by Shahar-Behalf** [zfcampus/zf-content-validation#61]
When the request payload is a string an InvalidArgumentException is being thrown by BaseInputFilter setData method since the provided data is not traversable.

In ContentValidationListener within onRoute method, where the BaseInputFilter setData method has been invoked (line 256, $inputFilter->setData($data);), there is no try/catch to catch the thrown InvalidArgumentException.
Therefore a 200 OK empty response is being returned instead of an exception.

**Comment by weierophinney** [comment]
The request payload comes from a `ZF\ContentNegotiation\ParameterDataContainer`, and will be pulled from one of either `getQueryParams()` or `getBodyParams()`, both of which can only return arrays; essentially, it's impossible for `setData()` to raise an exception here as a result.

What happens in the case you indicate is that zf-content-negotiation's `ContentTypeListener` is raising a fatal error because it is trying to pass a string to `ParameterDataContainer::setBodyParams()`; this is not being caught properly, resulting in an empty payload.

Please raise the issue on zf-content-negotiation, as we should be reporting a 400 error there if unable to parse the body, or, at the very least, leaving the the body parameters empty. Reference this comment when you do.
