### ISSUE TITLE
Rest content validation issue

### ISSUE THREAD

**Issue by developer-devPHP** [zfcampus/zf-content-validation#82]
In rest service (fetch all for example), if I seet **allows_only_fields_in_filter** for **GET** method
I will got this kind of error `Unrecognized fields: 0`
This because content something like this
```php
array (size=1)
  0 => 
    array (size=1)
      'server_name' => string 'asdasd'
```

if it is not a get method the content of values are this
```php
  array (size=1)
      'server_name' => string 'asdasd'
```

This problem just in REST fetch all, please have a look and tell me how I can fix this for now, before your update.

Thanks.

**Comment by developer-devPHP** [comment]
@weierophinney  Is it possible some quick fix in my end before global update?

**Comment by weierophinney** [comment]
> please have a look and tell me how I can fix this for now, before your update.

I'm not sure what you mean by this exactly... We don't have any planned updates for today, though we did an admin UI release a bit ago (unrelated to this).

I need more information, as I'm unsure how to reproduce the error, exactly. In particular, where do you get the error? Is it when requesting the API? or after submitting something via the admin UI? If via your API, can you provide:

- Directions showing how you created the input filter
- Directions demonstrating how you tried to invoke the API

That will help us reproduce and analyze the problem.

Thanks!

**Comment by weierophinney** [comment]
In an effort to try and reproduce, I've done the following:

- Started a new Apigility application
- Created a new API, Test
- Created a new RPC service for that API, Foo
- Created an input filter with a single field, `server_name`, which had a single validator (string length, allowing 3 - 140 chars)
- Edited the API's module configuration to:
  - Specify this new input filter as usable via GET for the specified controller service
  - enable the `allows_only_fields_in_filter` flag for the specified controller service

I then edited my controller's action to read as follows:

```php
public function fooAction()
{
    $event = $this->getEvent();
    $inputFilter = $event->getParam(\ZF\ContentValidation\InputFilter::class);
    return $inputFilter->getValues();
}
```

Finally, I tried accessing the service via each of:

- `/foo?server_name=fo` (which should not validate)
- `/foo?server_name=foobar` (which should validate)
- `/foo?server_name=foobar&my_name=mwop` (which invalidates due to extra values)

In each, it behaved as expected.

So, I need a reproduce case, and the version of zf-content-validation you're using.

Thanks!

**Comment by weierophinney** [comment]
Okay, I've managed to reproduce it.

- Created a new REST API, FooBar
- Created the same input filter as described in the previous comment, and configured it the same way.
- Updated the new resource's `fetchAll()` method to read as follows:

```php
public function fetchAll($params = [])
{
    $inputFilter = $this->getInputFilter();
    $entity = new FooBarEntity(array_merge($inputFilter->getValueS(), ['id' => uniqid()]));
    return new FooBarCollection(new \Zend\Paginator\Adapter\ArrayAdapter([$entity]));
}
```

I also updated `FooBarEntity` to extend `ArrayObject`.

Once I did that, I tried the following two requests:

- `/foo-bar?server_name=fo` — this correctly failed validation
- `/foo-bar?server_name=foobar` — **this demonstrated the issue reported**
- `/foo-bar?server_name=foobar&my_name=mwop` — this also demonstrated the issue

I *think* this likely makes sense, as operations on the resource *collection* should be submitting *collections*, and not individual entity fields.

Indeed, when I then modify the `fetch()` method to do the same (though using the provided `$id` value in the returned payload, and returning only the entity itself), it works correctly.

The question is whether or not we should allow validating *non*-collections when operating on *collection* endpoints. My personal take is that we shouldn't, and any such validation should be handled by the end-user (usually via a resource listener).

**Comment by webimpress** [comment]
@weierophinney Please have a look on my fix in #83.

It's very late so I'll try to write shortly:
- params passed to `fetchAll` method are not collection - what will be the point of having there collection of params? This is method GET so these params should be used as some kind of filters.
(For example `/album?name=FooBar` should returns all albums with name `FooBar`).

- `CollectionInputFilter` wrongly recognizes unknown fields (see: https://github.com/zendframework/zend-inputfilter/pull/115)

- There is another issue on posting collections, all is caused because `CollectionInputFilter` always returns all fields as unknown - please see #84

I'll explain more tomorrow if needed :)

**Comment by developer-devPHP** [comment]
I manually added #83 fixes and is is working, my issue is resolved.
Thanks @webimpress  
@weierophinney  are you going to merge this fix with master and create new release? If yes , when it should be done?
Thanks again for quick responce.

**Comment by weierophinney** [comment]
@developer-devPHP We'll have a release today, likely in the next hour.
